// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHousing.API.Database.Context;

namespace smart_housing_aspnet.Migrations
{
    [DbContext(typeof(SmartHousingContext))]
    [Migration("20190414153434_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Electricity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("TarriffId");

                    b.HasKey("Id");

                    b.ToTable("Electricity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 8.2100000000000009,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8.9100000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 10.359999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 9.5099999999999998,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 9.9100000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 7.21,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 7.5599999999999996,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 7.9100000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 8.5099999999999998,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 9.5600000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 8.9100000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 6.9100000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 8.5099999999999998,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 8.9100000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 7.5599999999999996,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 7.21,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 8.5099999999999998,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 3.5600000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 6.21,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 6.9100000000000001,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 21,
                            Amount = 6.5099999999999998,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 22,
                            Amount = 8.5600000000000005,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 23,
                            Amount = 7.21,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 24,
                            Amount = 6.21,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 25,
                            Amount = 8.5600000000000005,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 26,
                            Amount = 9.5099999999999998,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 27,
                            Amount = 11.56,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 28,
                            Amount = 8.6899999999999995,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 29,
                            Amount = 7.2699999999999996,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 30,
                            Amount = 8.3100000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 31,
                            Amount = 7.6900000000000004,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 32,
                            Amount = 9.1099999999999994,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 33,
                            Amount = 10.869999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = 7.9100000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 35,
                            Amount = 9.0099999999999998,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 36,
                            Amount = 9.1199999999999992,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 37,
                            Amount = 10.06,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 38,
                            Amount = 6.9800000000000004,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 39,
                            Amount = 7.3200000000000003,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 7.3099999999999996,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 41,
                            Amount = 8.8900000000000006,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 42,
                            Amount = 9.3399999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 43,
                            Amount = 7.96,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 44,
                            Amount = 7.6100000000000003,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 45,
                            Amount = 8.6099999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 46,
                            Amount = 7.9000000000000004,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 47,
                            Amount = 8.3100000000000005,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 48,
                            Amount = 9.3699999999999992,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 49,
                            Amount = 10.279999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 50,
                            Amount = 9.4900000000000002,
                            TarriffId = 3
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.ElectricityTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ElectricityTariffEnum");

                    b.Property<double?>("HighTarrif");

                    b.Property<double?>("LowTarrif");

                    b.Property<double?>("OneTarrif");

                    b.Property<double>("SupplyFee");

                    b.HasKey("Id");

                    b.ToTable("ElectricityTariff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElectricityTariffEnum = 1,
                            OneTarrif = 0.22,
                            SupplyFee = 10.0
                        },
                        new
                        {
                            Id = 2,
                            ElectricityTariffEnum = 2,
                            HighTarrif = 0.12,
                            LowTarrif = 0.23999999999999999,
                            SupplyFee = 10.0
                        },
                        new
                        {
                            Id = 3,
                            ElectricityTariffEnum = 3,
                            HighTarrif = 0.080000000000000002,
                            LowTarrif = 0.16,
                            SupplyFee = 41.299999999999997
                        },
                        new
                        {
                            Id = 4,
                            ElectricityTariffEnum = 4,
                            OneTarrif = 0.13,
                            SupplyFee = 5.7999999999999998
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5598d4b3-00b5-4c92-b78e-f97294cf75cc",
                            Email = "tomokulusic@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Kulusic",
                            LockoutEnabled = false,
                            Name = "Tomislav",
                            PasswordHash = "AQAAAAEAACcQAAAAEHj/UeLVYx8rYkAxpdYRgxO3YT3BOBwzsyaKk4PxneA5tx1Wshlhif+arIJ79JsTqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            TwoFactorEnabled = false,
                            UserName = "tomokulusic"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58403128-074c-44d2-8438-7f9d04d5fae9",
                            Email = "petar.kleskovic@enum.hr",
                            EmailConfirmed = false,
                            LastName = "Kleskovic",
                            LockoutEnabled = false,
                            Name = "Petar",
                            PasswordHash = "AQAAAAEAACcQAAAAEAqI7G1pQeQ/2sSunvu+V/8rJkRvyyhUxjYukozlsB3I+XwjxGz7ZWgtpBBxPJcJkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            TwoFactorEnabled = false,
                            UserName = "petar.kleskovic"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85a4f629-3dd5-4520-a503-fab3415d7f05",
                            Email = "kxl9597@g.rit.edu",
                            EmailConfirmed = false,
                            LastName = "Lucijanovic",
                            LockoutEnabled = false,
                            Name = "Klara",
                            PasswordHash = "AQAAAAEAACcQAAAAEDZLjSj+efHv21VCUrif6qSPXHjP3df3yj8r6OlMF7AQUqX6lw8mr6Ile33wCyOgHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            TwoFactorEnabled = false,
                            UserName = "kxl9597"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b419c457-9580-4503-b595-17819f74c60a",
                            Email = "stipe.brzi@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Brzica",
                            LockoutEnabled = false,
                            Name = "Stjepan",
                            PasswordHash = "AQAAAAEAACcQAAAAEIZeJ5bbSXsDJqDj+5vZn3e78Vz03FFNR+FDQwA3fCEcP3rHgibXx++LerDgH7AaRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            TwoFactorEnabled = false,
                            UserName = "stipe.brzi"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "19d5bf5c-cd03-4e47-a470-22073f076b25",
                            Email = "frano.nola@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Nola",
                            LockoutEnabled = false,
                            Name = "Frano",
                            PasswordHash = "AQAAAAEAACcQAAAAEMja3Hvpz03jeAUI0QUcHFUxIdtXWq+T30bijfH5a4TUpgZkXd0qRKJ8BzerjOZ9ZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            TwoFactorEnabled = false,
                            UserName = "frano.nola"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2543b476-2eb4-4d69-a276-9745ff347018",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            LastName = "User",
                            LockoutEnabled = false,
                            Name = "User",
                            PasswordHash = "AQAAAAEAACcQAAAAEJMCj6bMd8GhZbS7RNL+43LlOJo0IfY79qRVB6P4fxaXfMT8eAgJ7JYnrpKIcqz+Yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("ElectricityId");

                    b.Property<int>("SmartHouseCityRegion");

                    b.Property<int>("UserId");

                    b.Property<int>("UtilityType");

                    b.Property<int?>("WaterId");

                    b.HasKey("Id");

                    b.HasIndex("ElectricityId");

                    b.HasIndex("WaterId");

                    b.ToTable("Utilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 53.210000000000001,
                            Date = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 1,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 43.210000000000001,
                            Date = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 2,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 65.109999999999999,
                            Date = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 3,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 112.20999999999999,
                            Date = new DateTime(2019, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 4,
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 156.91,
                            Date = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 5,
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 157.11000000000001,
                            Date = new DateTime(2019, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 6,
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 87.909999999999997,
                            Date = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 7,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 56.509999999999998,
                            Date = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 8,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 51.210000000000001,
                            Date = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 9,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 78.900000000000006,
                            Date = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 10,
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 11.210000000000001,
                            Date = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 11,
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 56.880000000000003,
                            Date = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 12,
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 51.560000000000002,
                            Date = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 13,
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 14,
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 15,
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 16,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 17,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 18,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 60.810000000000002,
                            Date = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 19,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 20,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 21,
                            Amount = 41.899999999999999,
                            Date = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 21,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 22,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 22,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 23,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 23,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 24,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 151.99000000000001,
                            Date = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 25,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 26,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 26,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 27,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 27,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 28,
                            Amount = 51.210000000000001,
                            Date = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 28,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 29,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 29,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 30,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 30,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 31,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 121.91,
                            Date = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 2
                        },
                        new
                        {
                            Id = 33,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 3
                        },
                        new
                        {
                            Id = 34,
                            Amount = 51.210000000000001,
                            Date = new DateTime(2019, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 4
                        },
                        new
                        {
                            Id = 35,
                            Amount = 151.99000000000001,
                            Date = new DateTime(2019, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 5
                        },
                        new
                        {
                            Id = 36,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 6
                        },
                        new
                        {
                            Id = 37,
                            Amount = 41.899999999999999,
                            Date = new DateTime(2019, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 7
                        },
                        new
                        {
                            Id = 38,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 8
                        },
                        new
                        {
                            Id = 39,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 9
                        },
                        new
                        {
                            Id = 40,
                            Amount = 60.810000000000002,
                            Date = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 10
                        },
                        new
                        {
                            Id = 41,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 11
                        },
                        new
                        {
                            Id = 42,
                            Amount = 87.219999999999999,
                            Date = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 12
                        },
                        new
                        {
                            Id = 43,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 13
                        },
                        new
                        {
                            Id = 44,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 14
                        },
                        new
                        {
                            Id = 45,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 15
                        },
                        new
                        {
                            Id = 46,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 16
                        },
                        new
                        {
                            Id = 47,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 17
                        },
                        new
                        {
                            Id = 48,
                            Amount = 41.899999999999999,
                            Date = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 18
                        },
                        new
                        {
                            Id = 49,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 19
                        },
                        new
                        {
                            Id = 50,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 20
                        },
                        new
                        {
                            Id = 51,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 21
                        },
                        new
                        {
                            Id = 52,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 22
                        },
                        new
                        {
                            Id = 53,
                            Amount = 60.810000000000002,
                            Date = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 23
                        },
                        new
                        {
                            Id = 54,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 24
                        },
                        new
                        {
                            Id = 55,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 25
                        },
                        new
                        {
                            Id = 56,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 26
                        },
                        new
                        {
                            Id = 57,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 27
                        },
                        new
                        {
                            Id = 58,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 28
                        },
                        new
                        {
                            Id = 59,
                            Amount = 71.209999999999994,
                            Date = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 29
                        },
                        new
                        {
                            Id = 60,
                            Amount = 81.980000000000004,
                            Date = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 30
                        },
                        new
                        {
                            Id = 61,
                            Amount = 91.719999999999999,
                            Date = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 31,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 62,
                            Amount = 90.709999999999994,
                            Date = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 31
                        },
                        new
                        {
                            Id = 63,
                            Amount = 61.719999999999999,
                            Date = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 32,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 64,
                            Amount = 71.890000000000001,
                            Date = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 32
                        },
                        new
                        {
                            Id = 65,
                            Amount = 92.609999999999999,
                            Date = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 33,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 66,
                            Amount = 89.010000000000005,
                            Date = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 33
                        },
                        new
                        {
                            Id = 67,
                            Amount = 71.510000000000005,
                            Date = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 34,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 68,
                            Amount = 81.209999999999994,
                            Date = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 34
                        },
                        new
                        {
                            Id = 69,
                            Amount = 71.849999999999994,
                            Date = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 35,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 70,
                            Amount = 49.210000000000001,
                            Date = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 35
                        },
                        new
                        {
                            Id = 71,
                            Amount = 59.609999999999999,
                            Date = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 36,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 72,
                            Amount = 95.209999999999994,
                            Date = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 36
                        },
                        new
                        {
                            Id = 73,
                            Amount = 72.310000000000002,
                            Date = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 37,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 74,
                            Amount = 86.569999999999993,
                            Date = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 37
                        },
                        new
                        {
                            Id = 75,
                            Amount = 71.930000000000007,
                            Date = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 38,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 76,
                            Amount = 96.209999999999994,
                            Date = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 38
                        },
                        new
                        {
                            Id = 77,
                            Amount = 61.82,
                            Date = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 39,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 78,
                            Amount = 85.920000000000002,
                            Date = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 39
                        },
                        new
                        {
                            Id = 79,
                            Amount = 81.930000000000007,
                            Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 40,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 80,
                            Amount = 85.709999999999994,
                            Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 40
                        },
                        new
                        {
                            Id = 81,
                            Amount = 78.689999999999998,
                            Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 41,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 82,
                            Amount = 81.269999999999996,
                            Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 41
                        },
                        new
                        {
                            Id = 83,
                            Amount = 85.790000000000006,
                            Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 42,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 84,
                            Amount = 68.920000000000002,
                            Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 42
                        },
                        new
                        {
                            Id = 85,
                            Amount = 96.650000000000006,
                            Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 43,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 86,
                            Amount = 69.819999999999993,
                            Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 43
                        },
                        new
                        {
                            Id = 87,
                            Amount = 71.799999999999997,
                            Date = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 44,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 88,
                            Amount = 61.719999999999999,
                            Date = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 44
                        },
                        new
                        {
                            Id = 89,
                            Amount = 72.890000000000001,
                            Date = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 45,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 90,
                            Amount = 86.319999999999993,
                            Date = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 45
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Water", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("TarriffId");

                    b.HasKey("Id");

                    b.ToTable("Water");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0.20999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.22,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0.35999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 0.31,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0.23000000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 0.26000000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 0.16,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 0.20999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 0.31,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 0.16,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 0.11,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 0.91000000000000003,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 0.13,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 0.31,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 0.26000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 0.20999999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 0.19,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 0.20000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 0.17000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 0.27000000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 21,
                            Amount = 0.23000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 22,
                            Amount = 0.26000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 23,
                            Amount = 0.20999999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 0.27000000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 0.16,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 26,
                            Amount = 0.14000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 27,
                            Amount = 0.35999999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 28,
                            Amount = 0.20999999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 29,
                            Amount = 0.31,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 30,
                            Amount = 0.17999999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 31,
                            Amount = 0.28000000000000003,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 0.31,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 33,
                            Amount = 0.20999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = 0.12,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 35,
                            Amount = 0.17000000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = 0.22,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 37,
                            Amount = 0.14999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 38,
                            Amount = 0.12,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 39,
                            Amount = 0.28999999999999998,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 0.20999999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 41,
                            Amount = 0.22,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 42,
                            Amount = 0.23000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 43,
                            Amount = 0.20999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 44,
                            Amount = 0.32000000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 45,
                            Amount = 0.32000000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 46,
                            Amount = 0.25,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 47,
                            Amount = 0.14999999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 48,
                            Amount = 0.28000000000000003,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 49,
                            Amount = 0.23000000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 50,
                            Amount = 0.17000000000000001,
                            TarriffId = 2
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.WaterTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Tariff");

                    b.Property<int>("WaterTariffEnum");

                    b.HasKey("Id");

                    b.ToTable("WaterTariff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tariff = 11.949999999999999,
                            WaterTariffEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            Tariff = 20.93,
                            WaterTariffEnum = 2
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<int>");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            Name = "User",
                            NormalizedName = "user"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "96c90590-2b46-4580-826f-a0dda13be6f4",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<int>");

                    b.Property<int>("Id");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2,
                            Id = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            Id = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2,
                            Id = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2,
                            Id = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2,
                            Id = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 1,
                            Id = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Utility", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.Electricity", "Electricity")
                        .WithMany()
                        .HasForeignKey("ElectricityId");

                    b.HasOne("SmartHousing.API.Bal.Models.Water", "Water")
                        .WithMany()
                        .HasForeignKey("WaterId");
                });
#pragma warning restore 612, 618
        }
    }
}
