// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHousing.API.Database.Context;

namespace smart_housing_aspnet.Migrations
{
    [DbContext(typeof(SmartHousingContext))]
    partial class SmartHousingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Electricity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("TarriffId");

                    b.HasKey("Id");

                    b.ToTable("Electricity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.20999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 81.209999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 111.56,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 131.50999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 95.909999999999997,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 71.209999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 78.560000000000002,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 71.909999999999997,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 87.510000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 90.560000000000002,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 81.909999999999997,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 67.909999999999997,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 89.510000000000005,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 86.909999999999997,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 71.560000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 78.209999999999994,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 89.510000000000005,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 34.560000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 62.210000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 69.909999999999997,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 21,
                            Amount = 67.510000000000005,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 22,
                            Amount = 81.560000000000002,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 23,
                            Amount = 51.210000000000001,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 24,
                            Amount = 56.210000000000001,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 25,
                            Amount = 89.560000000000002,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 26,
                            Amount = 69.510000000000005,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 27,
                            Amount = 41.560000000000002,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 28,
                            Amount = 81.209999999999994,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 29,
                            Amount = 71.209999999999994,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 30,
                            Amount = 78.510000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 31,
                            Amount = 46.609999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 32,
                            Amount = 69.109999999999999,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 33,
                            Amount = 54.210000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = 79.609999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 35,
                            Amount = 91.909999999999997,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 36,
                            Amount = 99.120000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 37,
                            Amount = 101.91,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 38,
                            Amount = 60.979999999999997,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 39,
                            Amount = 71.310000000000002,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 75.909999999999997,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 41,
                            Amount = 68.390000000000001,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 42,
                            Amount = 91.540000000000006,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 43,
                            Amount = 71.959999999999994,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 44,
                            Amount = 72.609999999999999,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 45,
                            Amount = 81.609999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 46,
                            Amount = 76.900000000000006,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 47,
                            Amount = 28.309999999999999,
                            TarriffId = 3
                        },
                        new
                        {
                            Id = 48,
                            Amount = 79.370000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 49,
                            Amount = 61.280000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 50,
                            Amount = 39.909999999999997,
                            TarriffId = 3
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.ElectricityTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ElectricityTariffEnum");

                    b.Property<double?>("HighTarrif");

                    b.Property<double?>("LowTarrif");

                    b.Property<double?>("OneTarrif");

                    b.Property<double>("SupplyFee");

                    b.HasKey("Id");

                    b.ToTable("ElectricityTariff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ElectricityTariffEnum = 1,
                            OneTarrif = 0.22,
                            SupplyFee = 10.0
                        },
                        new
                        {
                            Id = 2,
                            ElectricityTariffEnum = 2,
                            HighTarrif = 0.12,
                            LowTarrif = 0.23999999999999999,
                            SupplyFee = 10.0
                        },
                        new
                        {
                            Id = 3,
                            ElectricityTariffEnum = 3,
                            HighTarrif = 0.080000000000000002,
                            LowTarrif = 0.16,
                            SupplyFee = 41.299999999999997
                        },
                        new
                        {
                            Id = 4,
                            ElectricityTariffEnum = 4,
                            OneTarrif = 0.13,
                            SupplyFee = 5.7999999999999998
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "484c134d-7ccc-42b2-bc97-2e765327cfa1",
                            Email = "tomokulusic@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEApDKCQhZUZqQSXGV5U2Sd/RskVh9zYuXGJBFRcabWyvQDlqkx6m08y8u2a3W8aEsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            TwoFactorEnabled = false,
                            UserName = "tomokulusic"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21e62275-a046-45ae-bdae-dbd1bfd6312d",
                            Email = "petar.kleskovic@enum.hr",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAENCpgJKOh1K+JMUCJVhRT+NfFESLzWyAFwqsFpfUDG+B4ySEELw+GxgoQThXNhM82g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            TwoFactorEnabled = false,
                            UserName = "petar.kleskovic"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ce3cc29-ed4d-49b6-8ddd-99a76b728d9f",
                            Email = "kxl9597@g.rit.edu",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEAllnN5K4H9djHePI+RB6E68YYJLRGuMp97F9IkknJYLQq82UZ3Py8hoeXX4tDuyPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            TwoFactorEnabled = false,
                            UserName = "kxl9597"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5a352dc-1175-45b4-ba44-ebf2e933087c",
                            Email = "stipe.brzi@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEAJybhNckEsN//+OlbvL6Csnw60/PmgLaegabujOIikjgZUkaQdFHxH+RzD8cgqKiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            TwoFactorEnabled = false,
                            UserName = "stipe.brzi"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d103325-db67-41d1-8bad-ba661b29cca2",
                            Email = "frano.nola@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFwMt1Hu8suKX60Zs4eNbQputgnP8oHi2ySDTdYq8TnX1WtXhc3L91RQSOy3VCFd5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            TwoFactorEnabled = false,
                            UserName = "frano.nola"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68215677-9542-4ce2-a4ba-c3c7c8b124d0",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEIIFJdIBzDla5el01b7iqg1k4BlIDCRoMz5raaZ0Io2iuu6h5m11SHUhxz7noAi7Ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("ElectricityId");

                    b.Property<int>("SmartHouseCityRegion");

                    b.Property<int>("UserId");

                    b.Property<int>("UtilityType");

                    b.Property<int?>("WaterId");

                    b.HasKey("Id");

                    b.HasIndex("ElectricityId");

                    b.HasIndex("WaterId");

                    b.ToTable("Utilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 53.210000000000001,
                            Date = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 1,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 43.210000000000001,
                            Date = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 2,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 65.109999999999999,
                            Date = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 3,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 112.20999999999999,
                            Date = new DateTime(2019, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 4,
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 156.91,
                            Date = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 5,
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 157.11000000000001,
                            Date = new DateTime(2019, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 6,
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 87.909999999999997,
                            Date = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 7,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 56.509999999999998,
                            Date = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 8,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 51.210000000000001,
                            Date = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 9,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 78.900000000000006,
                            Date = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 10,
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 11.210000000000001,
                            Date = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 11,
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 56.880000000000003,
                            Date = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 12,
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 51.560000000000002,
                            Date = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 13,
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 14,
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 15,
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 16,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 17,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 18,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 60.810000000000002,
                            Date = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 19,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 20,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 21,
                            Amount = 41.899999999999999,
                            Date = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 21,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 22,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 22,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 23,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 23,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 24,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 151.99000000000001,
                            Date = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 25,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 26,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 26,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 27,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 27,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 28,
                            Amount = 51.210000000000001,
                            Date = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 28,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 29,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 29,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 30,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 30,
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 31,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 121.91,
                            Date = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 2
                        },
                        new
                        {
                            Id = 33,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 3
                        },
                        new
                        {
                            Id = 34,
                            Amount = 51.210000000000001,
                            Date = new DateTime(2019, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 4
                        },
                        new
                        {
                            Id = 35,
                            Amount = 151.99000000000001,
                            Date = new DateTime(2019, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 5
                        },
                        new
                        {
                            Id = 36,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 6
                        },
                        new
                        {
                            Id = 37,
                            Amount = 41.899999999999999,
                            Date = new DateTime(2019, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 7
                        },
                        new
                        {
                            Id = 38,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 8
                        },
                        new
                        {
                            Id = 39,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 9
                        },
                        new
                        {
                            Id = 40,
                            Amount = 60.810000000000002,
                            Date = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 10
                        },
                        new
                        {
                            Id = 41,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 11
                        },
                        new
                        {
                            Id = 42,
                            Amount = 87.219999999999999,
                            Date = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 12
                        },
                        new
                        {
                            Id = 43,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 13
                        },
                        new
                        {
                            Id = 44,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 14
                        },
                        new
                        {
                            Id = 45,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 15
                        },
                        new
                        {
                            Id = 46,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 16
                        },
                        new
                        {
                            Id = 47,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 17
                        },
                        new
                        {
                            Id = 48,
                            Amount = 41.899999999999999,
                            Date = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 18
                        },
                        new
                        {
                            Id = 49,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 19
                        },
                        new
                        {
                            Id = 50,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 20
                        },
                        new
                        {
                            Id = 51,
                            Amount = 41.890000000000001,
                            Date = new DateTime(2019, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 21
                        },
                        new
                        {
                            Id = 52,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 22
                        },
                        new
                        {
                            Id = 53,
                            Amount = 60.810000000000002,
                            Date = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 23
                        },
                        new
                        {
                            Id = 54,
                            Amount = 78.909999999999997,
                            Date = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 24
                        },
                        new
                        {
                            Id = 55,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 25
                        },
                        new
                        {
                            Id = 56,
                            Amount = 111.20999999999999,
                            Date = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 26
                        },
                        new
                        {
                            Id = 57,
                            Amount = 56.780000000000001,
                            Date = new DateTime(2019, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 27
                        },
                        new
                        {
                            Id = 58,
                            Amount = 67.909999999999997,
                            Date = new DateTime(2019, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 28
                        },
                        new
                        {
                            Id = 59,
                            Amount = 71.209999999999994,
                            Date = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 29
                        },
                        new
                        {
                            Id = 60,
                            Amount = 81.980000000000004,
                            Date = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 30
                        },
                        new
                        {
                            Id = 61,
                            Amount = 91.719999999999999,
                            Date = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 31,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 62,
                            Amount = 90.709999999999994,
                            Date = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 31
                        },
                        new
                        {
                            Id = 63,
                            Amount = 61.719999999999999,
                            Date = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 32,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 64,
                            Amount = 71.890000000000001,
                            Date = new DateTime(2019, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 32
                        },
                        new
                        {
                            Id = 65,
                            Amount = 92.609999999999999,
                            Date = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 33,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 66,
                            Amount = 89.010000000000005,
                            Date = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 33
                        },
                        new
                        {
                            Id = 67,
                            Amount = 71.510000000000005,
                            Date = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 34,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 68,
                            Amount = 81.209999999999994,
                            Date = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 34
                        },
                        new
                        {
                            Id = 69,
                            Amount = 71.849999999999994,
                            Date = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 35,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 70,
                            Amount = 49.210000000000001,
                            Date = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 35
                        },
                        new
                        {
                            Id = 71,
                            Amount = 59.609999999999999,
                            Date = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 36,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 72,
                            Amount = 95.209999999999994,
                            Date = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 36
                        },
                        new
                        {
                            Id = 73,
                            Amount = 72.310000000000002,
                            Date = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 37,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 74,
                            Amount = 86.569999999999993,
                            Date = new DateTime(2019, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 37
                        },
                        new
                        {
                            Id = 75,
                            Amount = 71.930000000000007,
                            Date = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 38,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 76,
                            Amount = 96.209999999999994,
                            Date = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 38
                        },
                        new
                        {
                            Id = 77,
                            Amount = 61.82,
                            Date = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 39,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 78,
                            Amount = 85.920000000000002,
                            Date = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 39
                        },
                        new
                        {
                            Id = 79,
                            Amount = 81.930000000000007,
                            Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 40,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 80,
                            Amount = 85.709999999999994,
                            Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 40
                        },
                        new
                        {
                            Id = 81,
                            Amount = 78.689999999999998,
                            Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 41,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 82,
                            Amount = 81.269999999999996,
                            Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 4,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 41
                        },
                        new
                        {
                            Id = 83,
                            Amount = 85.790000000000006,
                            Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 42,
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 84,
                            Amount = 68.920000000000002,
                            Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 2,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 42
                        },
                        new
                        {
                            Id = 85,
                            Amount = 96.650000000000006,
                            Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 43,
                            SmartHouseCityRegion = 1,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 86,
                            Amount = 69.819999999999993,
                            Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 8,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 43
                        },
                        new
                        {
                            Id = 87,
                            Amount = 71.799999999999997,
                            Date = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 44,
                            SmartHouseCityRegion = 6,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 88,
                            Amount = 61.719999999999999,
                            Date = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 3,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 44
                        },
                        new
                        {
                            Id = 89,
                            Amount = 72.890000000000001,
                            Date = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ElectricityId = 45,
                            SmartHouseCityRegion = 7,
                            UserId = 0,
                            UtilityType = 2
                        },
                        new
                        {
                            Id = 90,
                            Amount = 86.319999999999993,
                            Date = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmartHouseCityRegion = 5,
                            UserId = 0,
                            UtilityType = 1,
                            WaterId = 45
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Water", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int>("TarriffId");

                    b.HasKey("Id");

                    b.ToTable("Water");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.20999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150.21000000000001,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 111.56,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 131.50999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 95.909999999999997,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 71.209999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 78.560000000000002,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 222.91,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 87.510000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 90.560000000000002,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 111.91,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 135.91,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 190.50999999999999,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 221.91,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 115.56,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 78.209999999999994,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 89.510000000000005,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 34.560000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 120.20999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 123.91,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 21,
                            Amount = 167.50999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 22,
                            Amount = 241.56,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 23,
                            Amount = 231.21000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 56.210000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 89.560000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 26,
                            Amount = 69.510000000000005,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 27,
                            Amount = 141.56,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 28,
                            Amount = 113.20999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 29,
                            Amount = 178.21000000000001,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 30,
                            Amount = 172.91,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 31,
                            Amount = 89.209999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 72.909999999999997,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 33,
                            Amount = 17.91,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = 79.120000000000005,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 35,
                            Amount = 68.569999999999993,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = 78.120000000000005,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 37,
                            Amount = 56.909999999999997,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 38,
                            Amount = 88.609999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 39,
                            Amount = 78.510000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 87.209999999999994,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 41,
                            Amount = 83.209999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 42,
                            Amount = 14.23,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 43,
                            Amount = 98.209999999999994,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 44,
                            Amount = 101.31999999999999,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 45,
                            Amount = 78.319999999999993,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 46,
                            Amount = 80.560000000000002,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 47,
                            Amount = 69.120000000000005,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 48,
                            Amount = 71.450000000000003,
                            TarriffId = 2
                        },
                        new
                        {
                            Id = 49,
                            Amount = 84.909999999999997,
                            TarriffId = 1
                        },
                        new
                        {
                            Id = 50,
                            Amount = 71.670000000000002,
                            TarriffId = 2
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.WaterTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Tariff");

                    b.Property<int>("WaterTariffEnum");

                    b.HasKey("Id");

                    b.ToTable("WaterTariff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tariff = 11.949999999999999,
                            WaterTariffEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            Tariff = 20.93,
                            WaterTariffEnum = 2
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<int>");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            Name = "User",
                            NormalizedName = "user"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "d3d84202-ab29-48cf-b7e9-db1cd1d5e1fd",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<int>");

                    b.Property<int>("Id");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2,
                            Id = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            Id = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2,
                            Id = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2,
                            Id = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2,
                            Id = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 1,
                            Id = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHousing.API.Bal.Models.Utility", b =>
                {
                    b.HasOne("SmartHousing.API.Bal.Models.Electricity", "Electricity")
                        .WithMany()
                        .HasForeignKey("ElectricityId");

                    b.HasOne("SmartHousing.API.Bal.Models.Water", "Water")
                        .WithMany()
                        .HasForeignKey("WaterId");
                });
#pragma warning restore 612, 618
        }
    }
}
